#!/usr/bin/env python

from boto.s3.connection import S3Connection
from boto.s3.key import Key
import os


def upload_file(source, destination):
  print 'Uploading ' + source + ' to ' + destination
  obj = bucket.new_key(destination)
  obj.set_contents_from_filename(source)
  obj.make_public()

def upload_folder(folder):
  for path,dir,files in os.walk(folder):
    for file in files:
      filePath = os.path.join(path,file)
      destination = filePath[len(folder)+1:]
      upload_file(filePath, destination)

aws_access_key_id=os.environ['AWS_ACCESS_KEY']
aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY']
connection = S3Connection(aws_access_key_id, aws_secret_access_key)
bucket = connection.get_bucket('clockwise.ee')

upload_folder('dist')
